### ISSUE TITLE
Wrong position show in highscore table 

### ISSUE THREAD

**Issue by tuliodnw** [TheSunCat/Sudoku#18] opened 2023-09-13 08:20 UTC
![Screenshot_20230913-101426](https://github.com/TheSunCat/Sudoku/assets/18468905/44cdc50f-5093-4bcd-96c5-68dccdcba4e9)

At the winning screen, position 3 and 4 have the same time. But the the incorrect date was highlighted.

**Comment by AstralShadow** [comment] 2023-09-26 15:13
Hello @tuliodnw,

Thanks for the report!

Your issue seems to be a duplicate of #12.
Are you sure you're running the latest release of the game?

**Comment by TheSunCat** [comment] 2023-10-12 19:24
I can indeed reproduce this on the latest game version, using my high-speed extreme solving skills:
![image](https://github.com/TheSunCat/Sudoku/assets/44881120/9bca8645-6b00-410e-82a6-426b9b0e6f93)

Working on a fix now.

**Closed** 2023-10-12 20:02 UTC
